# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('active_start_date', models.DateField(verbose_name=b'Active Start Date')),
                ('active_end_date', models.DateField(blank=True, null=True, verbose_name=b'Active End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name=b'Project Name')),
                ('active_start_date', models.DateField(verbose_name=b'Active Start Date')),
                ('active_end_date', models.DateField(blank=True, null=True, verbose_name=b'Active End Date')),
                ('description', models.TextField(blank=True, verbose_name=b'Description')),
                ('client_name', models.CharField(max_length=254, verbose_name=b'Name of Client')),
                ('git_url', models.URLField(verbose_name=b'Git URL')),
                ('testing_url', models.URLField(blank=True, verbose_name=b'Testing URL')),
                ('production_url', models.URLField(blank=True, verbose_name=b'Production URL')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=254, verbose_name=b'Version Number')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Library', verbose_name=b'Library')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project', verbose_name=b'Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='libraries',
            field=models.ManyToManyField(blank=True, through='api.ProjectLibrary', to='api.Library', verbose_name=b'Project Library'),
        ),
    ]
